In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
plt.rcParams['figure.figsize'] = (6,6)

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

from keras.layers import Dense, Input, Activation, Conv1D
from keras.layers import Dropout, MaxPooling1D, Flatten, Concatenate, Reshape
from keras.models import Sequential, Model, load_model
from keras.callbacks import ModelCheckpoint, EarlyStopping
from keras.utils import np_utils

import re
import random
import os

Using TensorFlow backend.


In [2]:
def vectorize_train(training_documents):
    # Initialize the TfidfVectorizer model and document-term matrix
    vectorizer = TfidfVectorizer()
    tfidf_train = None
    # [YOUR CODE HERE]
    tfidf_train = vectorizer.fit_transform(training_documents)
    return vectorizer, tfidf_train

def load_as_list(fname):
    df = pd.read_csv(fname)
    id = df['id'].values.tolist()
    label = df['label'].values.tolist()
    tweets = df['tweet'].values.tolist()
    return tweets, label

In [3]:
tweets, label = load_as_list("train.csv")

vectorizer, tf_idf = vectorize_train(tweets)

tfidf = TfidfVectorizer(binary=True)

x = tfidf.fit_transform(tweets).todense()
print(x)

print(x.shape)



[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(31962, 41392)


In [4]:
model = Sequential([
    Dense(32, activation='relu', input_shape=(41392,)),
    Dense(1, activation='softmax'),
])

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])
model.fit(
    x,
    label,
    batch_size=32,
    epochs=10, verbose=2,
    callbacks=None,
    validation_split=0.2,
    validation_data=None,
    shuffle=True,
    class_weight=None,
    sample_weight=None,
    initial_epoch=0)

model.summary()

ERROR! Session/line number was not unique in database. History logging moved to new session 58
Train on 25569 samples, validate on 6393 samples
Epoch 1/10
 - 51s - loss: 14.2550 - accuracy: 0.0703 - val_loss: 14.1902 - val_accuracy: 0.0695
Epoch 2/10
 - 40s - loss: 14.2550 - accuracy: 0.0703 - val_loss: 14.1902 - val_accuracy: 0.0695
Epoch 3/10
 - 36s - loss: 14.2550 - accuracy: 0.0703 - val_loss: 14.1902 - val_accuracy: 0.0695
Epoch 4/10
 - 36s - loss: 14.2550 - accuracy: 0.0703 - val_loss: 14.1902 - val_accuracy: 0.0695
Epoch 5/10
 - 35s - loss: 14.2550 - accuracy: 0.0703 - val_loss: 14.1902 - val_accuracy: 0.0695
Epoch 6/10
 - 34s - loss: 14.2550 - accuracy: 0.0703 - val_loss: 14.1902 - val_accuracy: 0.0695
Epoch 7/10
 - 35s - loss: 14.2550 - accuracy: 0.0703 - val_loss: 14.1902 - val_accuracy: 0.0695
Epoch 8/10
 - 35s - loss: 14.2550 - accuracy: 0.0703 - val_loss: 14.1902 - val_accuracy: 0.0695
Epoch 9/10
 - 34s - loss: 14.2550 - accuracy: 0.0703 - val_loss: 14.1902 - val_accuracy:

In [1]:
pwd

'C:\\Users\\Amaan_Hussain\\Desktop\\UIC Research'